
data:
  file_path: "./crawling/data/geeknews.csv"

split:
  chunk_type: recursive
  chunk_size: 1000
  chunk_overlap: 50

embedding:
  backend: openai
  model: embedding-query
  chunk_size: 100

vectordb:
  #backend: faiss
  backend: qdrant
  client:
    host: localhost
    port: 50333
  collection_name: faiss_automated_import

llm:
  model: solar-pro2